apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthsync-pr-deployment
  labels:
    app: healthsync-pr-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: healthsync-pr-service
  template:
    metadata:
      labels:
        app: healthsync-pr-service
    spec:
      containers:
        - name: healthsync-pr-container
          image: your-dockerhub-username/healthsync-pr-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://<DB_HOST>:3306/<DB_NAME>"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: healthsync-pr-service
spec:
  type: LoadBalancer
  selector:
    app: healthsync-pr-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080